### ISSUE TITLE
Resolve network outage in the CI lab

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#1800] opened 2023-11-17 18:32 UTC
Currently we've lost all of our Macs due to networking issues in the CI lab. Since it's late Friday in EU we're unlikely to see a resolution before Monday.

**Comment by fweikert** [comment] 2023-11-20 13:37
Update: Most Macs are slowly coming back online. Due to the long duration of the outage we've accumulated a significant backlog of jobs :(

**Comment by fweikert** [comment] 2023-11-20 13:55
Clarification: CI simply skips MacOS tasks for most of the pipelines, since we thought this would be less disruptive than failing. As a result, there's a chance that any change that is being merged now will cause MacOS breakages later. However, we hope that full MacOS testing will be possible at the end of the week - then we can find breakages via post-submit pipelines.

**Comment by meteorcloudy** [comment] 2023-11-28 14:11
/cc @keith @BalestraPatrick Sorry for not pinging you already. But this has already affected rules_python. Some commits have been merged without actually going through CI test.

![image](https://github.com/bazelbuild/continuous-integration/assets/4171702/97299f30-6b20-4ea5-a8d1-ff75b09a2e71)

**Comment by keith** [comment] 2023-11-28 17:59
ah yea. in our case instead of filtering out the jobs we'd probably prefer they fail, but that might be unique to us since we disproportionally care about apple support. we have a branch protection on the overall job but since that ended up being green we didn't notice

**Comment by meteorcloudy** [comment] 2023-11-29 12:26
Yeah, for now you'll have to assume you don't have CI coverage at all for apple rules. I'm hoping we can get at least postsubmit working today. Will update here.

**Comment by meteorcloudy** [comment] 2023-12-06 09:59
Unfortunately, the issue is still ongoing... we are still working on fixing it

**Comment by keith** [comment] 2023-12-18 18:58
any news?

**Comment by brandjon** [comment] 2023-12-20 14:47
I'm seeing a dns failure on mac on [presubmit](https://buildkite.com/bazel/google-bazel-presubmit/builds/75177#018c87a9-f3ed-416a-961d-b39d10ed36ed). Is that known / expected, or a separate issue?

```sh
$ git --git-dir /usr/local/var/bazelbuild/https---bazel-googlesource-com-bazel-git fetch origin master
fatal: unable to access 'https://bazel.googlesource.com/bazel.git/': Could not resolve host: bazel.googlesource.com
```

**Comment by fweikert** [comment] 2023-12-20 17:18
@brandjon Looks like a transient error while Yun was fixing the network. Can you please retry?

**Closed** 2023-12-20 17:29 UTC
Labels: bug, P0

**Comment by brandjon** [comment] 2023-12-20 18:48
Yeah, [different failure mode now](https://buildkite.com/bazel/google-bazel-presubmit/builds/75195#018c8867-ea4d-40f3-b69c-ddd84cb6d95e), instead of all shards having dns trouble.

```
gRPC server failed to bind to IPv4 and IPv6 localhosts on port 0: [IPv4] Failed to bind to address /127.0.0.1:0
[IPv6] Failed to bind to address /[0:0:0:0:0:0:0:1]:0
com.google.devtools.build.lib.util.AbruptExitException: gRPC server failed to bind to IPv4 and IPv6 localhosts on port 0: [IPv4] Failed to bind to address /127.0.0.1:0
[IPv6] Failed to bind to address /[0:0:0:0:0:0:0:1]:0
	at com.google.devtools.build.lib.server.GrpcServerImpl.serve(GrpcServerImpl.java:438)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.serverMain(BlazeRuntime.java:1068)
	at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:771)
	at com.google.devtools.build.lib.bazel.Bazel.main(Bazel.java:95)
Caused by: java.io.IOException: Failed to bind to address /127.0.0.1:0
	at io.grpc.netty.NettyServer.start(NettyServer.java:328)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:183)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:92)
	at com.google.devtools.build.lib.server.GrpcServerImpl.serve(GrpcServerImpl.java:435)
	... 3 more
Caused by: java.net.SocketException: Operation not permitted
```

**Comment by Wyverald** [comment] 2023-12-20 19:15
I've found bk-imacpro-6 and bk-imacpro-4 especially prone to this specific failure. Maybe we should take them offline? As it is, them being online actually costs us more resources due to retries.

**Comment by fweikert** [comment] 2023-12-20 19:22
Technically https://github.com/bazelbuild/bazel/commit/2c51a0c8590e73c88d6a678f1b0583c6aee313c3 should have fixed this problem, but it's hard to see whether that change was in the tree used for presubmit. Post-submit looks fine (minus two unrelated failures)
