### ISSUE TITLE
Building Bazel on Ubuntu 18.04 (no JDK) fails in downstream

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#747] opened 2019-07-09 13:46 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1082#14e3c634-69a6-4a2f-8071-a95ea7faa40d
```

(13:41:43) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_google_protobuf/BUILD.bazel:313:1: Couldn't build file external/com_google_protobuf/_objs/protoc_lib/csharp_message_field.o: undeclared inclusion(s) in rule '@com_google_protobuf//:protoc_lib':
--
  | this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/compiler/csharp/csharp_message_field.cc':
  | '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
  | '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h'
  | '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
  | '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h'
  | '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h'


```

It succeeded after rerun, this looks like a cache problem?

And why are there two `Build Bazel (:ubuntu: 18.04 (no JDK))` jobs?

**Comment by philwo** [comment] 2019-07-09 13:49
> And why are there two Build Bazel (:ubuntu: 18.04 (no JDK)) jobs?

One tests with --javabase=<openjdk9> and the other tests with --javabase=<openjdk10>. They're defined here: https://github.com/bazelbuild/bazel/blob/master/.bazelci/presubmit.yml#L116

Unfortunately the name seems to get lost in the downstream pipeline.

**Comment by meteorcloudy** [comment] 2019-07-09 13:55
Ah, I see, thanks for the explain!

**Comment by meteorcloudy** [comment] 2019-07-18 11:40
Just saw similar error again:
https://buildkite.com/bazel/google-bazel-presubmit/builds/22264#e2a9caef-2d0b-4f70-996f-360513b2f946

**Comment by philwo** [comment] 2019-07-18 11:47
I don't know what could cause it :(

The Linux workers are now completely stateless, too (they shutdown after each job), so it can't be anything like accidentally kept local state.

If it only happens during presubmit and never during postsubmit, the obvious idea is that it is caused by remote caching.

Here's what goes into the remote cache silo key:

> --- :bazel: Computing flags for build step
> Adding to platform cache key: b'bazel'
> Adding to platform cache key: b'ubuntu1804_nojava'

Here's the command-line where we run Bazel:

> bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --terminal_columns=143 --show_timestamps --verbose_failures --keep_going --jobs=32 --announce_rc --experimental_multi_threaded_digest --experimental_repository_cache_hardlinks --disk_cache= --sandbox_tmpfs_path=/tmp --google_default_credentials --remote_cache=remotebuildexecution.googleapis.com --remote_instance_name=projects/bazel-untrusted/instances/default_instance --tls_enabled=true --remote_timeout=60 --remote_max_connections=200 --remote_default_platform_properties=properties:{name:"cache-silo-key" value:"e141f99d0a9dbf2981e93b14ca8fa0fc1855e50ea01c2a7c0d520da5b3bd369d"} --javabase=@openjdk10_linux_archive//:runtime //src:bazel //src:bazel_jdk_minimal

The build then immediately fails with errors like this:

> ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/com_google_protobuf/BUILD.bazel:158:1: Couldn't build file external/com_google_protobuf/_objs/protobuf/substitute.pic.o: undeclared inclusion(s) in rule '@com_google_protobuf//:protobuf':
> this rule is missing dependency declarations for the following files included by 'external/com_google_protobuf/src/google/protobuf/stubs/substitute.cc':
>   '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/limits.h'
>   '/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed/syslimits.h'

Maybe Bazel doesn't correctly compute the inputs that go into an action and accidentally shares a cached action across different versions of compilers?

**Comment by philwo** [comment] 2019-07-18 11:48
Here's also a very weird bug I remember: When I tried to bootstrap Bazel on ARM, I always got C++ include scanning errors like these, while I was still using the `--javabase` flag to point to the local system JDK. The errors went away, once I patched the correct OpenJDK directly into the WORKSPACE file, so Bazel could download it as required.

I have no idea how javabase and C++ compilation could be related, but this is what I saw...

**Comment by meteorcloudy** [comment] 2019-07-18 12:37
I logged into the Linux worker and launch the docker image, which can stably reproduce this problem. I found the following content in `bazel-workdir/external/local_config_cc/BUILD`
```
cc_toolchain_config(
    name = "local",
    cpu = "k8",
    compiler = "compiler",
    toolchain_identifier = "local",
    host_system_name = "local",
    target_system_name = "local",
    target_libc = "local",
    abi_version = "local",
    abi_libc_version = "local",
    cxx_builtin_include_directories = ["/usr/lib/gcc/x86_64-linux-gnu/5/include",
    "/usr/local/include",
    "/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed",
    "/usr/include/x86_64-linux-gnu",
    "/usr/include",
    "/usr/include/c++/5",
    "/usr/include/x86_64-linux-gnu/c++/5",
    "/usr/include/c++/5/backward"],
```

`/usr/include/x86_64-linux-gnu/c++/7` should be in `cxx_builtin_include_directories` instead of `/usr/include/x86_64-linux-gnu/c++/5`

After a `bazel clean --expunge`, the error went away.

**Comment by philwo** [comment] 2019-07-19 09:38
This should be fixed now with the new stateless workers.

**Closed by philwo** 2019-07-19 09:38 UTC
