### ISSUE TITLE
Android Testing fails on Windows with Bazel@HEAD

### ISSUE THREAD

**Issue by laszlocsomor** [bazelbuild/continuous-integration#924] opened 2020-01-23 08:11 UTC
At https://github.com/android/testing-samples/commit/7e31acea87325ff61b28c12d5c6dac513a2ece44 with Bazel@HEAD (https://github.com/bazelbuild/bazel/commit/5bfe4ba1e3411b08e3d2cfd8fed657d067c44043) on Windows, Android Testing is failing due to missing tools.

Filing it under https://github.com/bazelbuild/continuous-integration and not under https://github.com/android/testing-samples because I suspect a corrupt SDK installation.

```

(02:06:42) ERROR: missing input file 'external/androidsdk/build-tools/28.0.2/lib/dx.jar', owner: '@androidsdk//:build-tools/28.0.2/lib/dx.jar'
--
  | (02:06:42) ERROR: D:/b/hw27glvc/external/androidsdk/BUILD.bazel:8:1: @androidsdk//:dx_jar_import: missing input file '@androidsdk//:build-tools/28.0.2/lib/dx.jar'
  | (02:06:44) INFO: From Linking external/bazel_tools/src/main/native/windows/windows_jni.dll [for host]:
  | Creating library bazel-out/host/bin/external/bazel_tools/src/main/native/windows/windows_jni.dll.if.lib and object bazel-out/host/bin/external/bazel_tools/src/main/native/windows/windows_jni.dll.if.exp
  | (02:06:47) ERROR: missing input file 'external/androidsdk/build-tools/28.0.2/lib/apksigner.jar', owner: '@androidsdk//:build-tools/28.0.2/lib/apksigner.jar'
  | (02:06:47) ERROR: D:/b/hw27glvc/external/androidsdk/BUILD.bazel:8:1: @androidsdk//:apksigner: missing input file '@androidsdk//:build-tools/28.0.2/lib/apksigner.jar'
  | (02:06:47) ERROR: missing input file 'external/androidsdk/build-tools/28.0.2/aapt2.exe', owner: '@androidsdk//:build-tools/28.0.2/aapt2.exe'
  | (02:06:47) ERROR: missing input file 'external/androidsdk/build-tools/28.0.2/aapt2.exe', owner: '@androidsdk//:build-tools/28.0.2/aapt2.exe'
  | (02:06:47) ERROR: D:/b/bk-windows-java8-02bg/bazel-downstream-projects/android-testing/ui/espresso/BasicSample/BUILD.bazel:6:1: //ui/espresso/BasicSample:BasicSampleLib: missing input file '@androidsdk//:build-tools/28.0.2/aapt2.exe'
  | (02:06:47) ERROR: missing input file 'external/androidsdk/build-tools/28.0.2/aapt2.exe', owner: '@androidsdk//:build-tools/28.0.2/aapt2.exe'
  | (02:06:47) ERROR: D:/b/hw27glvc/external/maven/BUILD:143:1: @maven//:androidx_core_core_1_0_0: missing input file '@androidsdk//:build-tools/28.0.2/aapt2.exe'
(...)
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1361#c2a60939-df5c-4f49-83e8-29640aedab3e

**Comment by philwo** [comment] 2020-01-23 08:17
Hi,

thanks for reporting. This is a duplicate of https://github.com/bazelbuild/continuous-integration/issues/921. The Windows issue was fixed upstream (they pinned their build tools to a specific, no longer supported version). The project has to get their pipeline green to update the "last green commit" that's used in the downstream pipeline (Bazel@HEAD) though, so that it picks up that patch. It seems like their build has been red on Linux for ages, so I'm not too confident that it will happen soon.

**Closed by philwo** 2020-01-23 08:17 UTC

**Comment by laszlocsomor** [comment] 2020-01-23 08:21
Thanks for the clear explanation!
