### ISSUE TITLE
bazelisk-plus-incompatible-flags incorrectly reports that a flag needs migration

### ISSUE THREAD

**Issue by cushon** [bazelbuild/continuous-integration#589] opened 2019-03-27 15:11 UTC
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/58 says that `--incompatible_use_toolchain_providers_in_java_common` needs migration for the 'IntelliJ Plugin Aspect', but when I click through to the build I don't see any errors: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/58#4c5e6281-604e-47ab-875d-d2eec32e8cfe

```
bazel build --show_progress_rate_limit=5 --curses=yes --color=yes --verbose_failures --keep_going --jobs=32 --announce_rc --experimental_multi_threaded_digest --sandbox_tmpfs_path=/tmp --remote_timeout=60 --disk_cache= --remote_max_connections=200 --host_platform_remote_properties_override=properties:{name:"platform" value:"ubuntu1604"} --google_default_credentials --remote_http_cache=https://storage.googleapis.com/bazel-untrusted-buildkite-cache //aspect:aspect_files --incompatible_use_toolchain_providers_in_java_common
  | INFO: Invocation ID: 8e9201e7-bbcc-4be9-97df-871714f5d25c
  | INFO: Options provided by the client:
  | Inherited 'common' options: --isatty=1 --terminal_columns=0
  | INFO: Build option --incompatible_use_jdk11_as_host_javabase has changed, discarding analysis cache.
  | INFO: Analysed target //aspect:aspect_files (24 packages loaded, 691 targets configured).
  | INFO: Found 1 target...
  | Target //aspect:aspect_files up-to-date:
  | bazel-genfiles/aspect/intellij_info_bundled.bzl
  | bazel-genfiles/aspect/BUILD.bazel
  | bazel-bin/aspect/tools/JarFilter_deploy.jar
  | bazel-bin/aspect/tools/PackageParser_deploy.jar
  | INFO: Elapsed time: 1.478s, Critical Path: 1.05s
  | INFO: 5 processes: 5 remote cache hit.
  | INFO: Build completed successfully, 6 total actions
```

Am I mis-reading what the UI is telling me, or is there a bug in the way it's processing the build output?

**Comment by meteorcloudy** [comment] 2019-03-28 09:00
Duplicate of https://github.com/bazelbuild/continuous-integration/issues/590

**Closed by meteorcloudy** 2019-03-28 09:00 UTC
