### ISSUE TITLE
bazelci.py crashes with a UnicodeDecodeError

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/continuous-integration#239] opened 2018-03-02 11:51 UTC
Reported by Alex. Build: https://buildkite.com/bazel/rules-nodejs-nodejs/builds/72#d37cf401-9087-420d-8b18-ec523bb6d510

```
INFO: Build completed successfully, 103 total actions
 
🗑️ Cleanup
1s
 
bazel clean --expunge
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Traceback (most recent call last):
File "bazelci.py", line 1134, in <module>
sys.exit(main())
File "bazelci.py", line 1121, in main
args.build_only, args.test_only)
File "bazelci.py", line 365, in execute_commands
invocation_id = bes_invocation_id(build_bep_file)
File "bazelci.py", line 525, in bes_invocation_id
raw_data = f.read()
File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 335852: ordinal not in range(128)

```

**Comment by alexeagle** [comment] 2018-03-02 13:38
Note, rules_typescript is solid red on master due to this.

**Comment by buchgr** [comment] 2018-03-02 14:44
Thanks for reporting the issue and my apologies for the problem. It should be fixed now. https://buildkite.com/bazel/rules-nodejs-nodejs/builds/76

**Closed by buchgr** 2018-03-02 14:44 UTC

**Comment by buchgr** [comment] 2018-03-02 14:48
@alexeagle I think the `rules_typescript` error is unrelated to this? https://github.com/bazelbuild/rules_typescript/issues/159

**Comment by alexeagle** [comment] 2018-03-02 15:44
Yes the Mac failure was there previously, it's the ubuntu failure that was caused by this bug. Thanks for the quick fix
