### ISSUE TITLE
Windows test logs download instead of opening in browser

### ISSUE THREAD

**Issue by katre** [bazelbuild/continuous-integration#584] opened 2019-03-26 15:18 UTC
Example CI run:
https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/2259

The test failure logs for Windows ([example](https://buildkite.com/organizations/bazel/pipelines/bazel-bazel-github-presubmit/builds/2259/jobs/a8a441a3-697e-47b0-a745-9d0b0b8595d2/artifacts/0e23e872-9546-4e92-9b45-2d7563aa74cd)) download as files instead of displaying in the browser.

Test failure logs for Ubuntu ([example](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/ac5edbbc-43af-42c7-b2ec-29c7bf303846/src/test/java/com/google/devtools/build/lib/analysis_test/attempt_1.log)) do open in the browser.

**Comment by philwo** [comment] 2019-05-28 13:01
This is caused by gsutil uploading these logs as Content-Type "binary/octet-stream" instead of "text/plain" like it does on Linux. I'll see if we can manually override this.

**Comment by philwo** [comment] 2019-05-28 13:07
I had a look at the Buildkite Agent Code and it seems like this should work fine.

Also, on a more recent build, the log file was uploaded with the correct Content-Type, so that it can be viewed in the browser: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/a7cc711b-4751-4622-b01e-8321456aa68f/src%5Ctest%5Cpy%5Cbazel%5Ctest_wrapper_test%5Ctest.log

From: https://buildkite.com/bazel/bazel-bazel/builds/8464#a7cc711b-4751-4622-b01e-8321456aa68f

Closing this as fixed, let me know if you see this again.

**Closed by philwo** 2019-05-28 13:07 UTC
