### ISSUE TITLE
Request to add new project remote-apis-sdks

### ISSUE THREAD

**Issue by ifoox** [bazelbuild/continuous-integration#704] opened 2019-06-05 20:29 UTC
- I want to test the following project on Bazel CI: [URL_TO_GIT_HUB_PROJECT]
- I confirm that the project has a `.bazelci/presubmit.yml` file.

# Instructions (you can delete this section from the issue)

Welcome to Bazel CI! We are thrilled that you want to test your project with Bazel.
Please follow these steps to make the on-boarding experience as smooth as possible:

1. Add the URL of your project's GitHub repository to the first line of this issue.
2. Add the name of your project to the issue title.
3. Please read the [introduction to Buildkite](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md) to learn about the basic concepts such as pipelines.
4. Create and commit your presubmit configuration in `<YOUR REPO>/.bazelci/presubmit.yml`. The configuration format is documented [here](https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#configuring-a-pipeline), and you can find several an example [here](https://github.com/bazelbuild/rules_typescript/blob/master/.bazelci/presubmit.yml). No need to get it right on the first try - It's usually a good idea to start with a basic configuration, wait until the pipeline is set up, trigger a build and then iterate on the configuration.
5. The Bazel team will review this issue and create a pipeline on Buildkite.
6. The team will reach out to you and give you instructions on how to set up a GitHub webhook that triggers a CI build for incoming pull requests.

**Comment by philwo** [comment] 2019-06-05 20:42
Hi @ifoox,

I created a Buildkite pipeline for your repository, ran a first build (which passed 🎉) and added the webhook to your repository, so that you can presubmit testing for pull requests and postsubmit testing for all commits to branches work.

You can see the pipeline dashboard here: https://buildkite.com/bazel/remote-apis-sdks

The pipeline is publicly viewable without logging in, but I'll send you a Buildkite invite via e-mail that allows you to create an account. This will give you the necessary access to retry failed builds and manually trigger new builds, in case it's necessary.

If you want to add a build badge to your README.md, this is the code:

```markdown
[![Build Status](https://badge.buildkite.com/7aef818bbb87e72d81054de0d9151ffe4a4f6eb04b85eab106.svg?branch=master)](https://buildkite.com/bazel/remote-apis-sdks)
```

It looks like this: [![Build Status](https://badge.buildkite.com/7aef818bbb87e72d81054de0d9151ffe4a4f6eb04b85eab106.svg)](https://buildkite.com/bazel/remote-apis-sdks)

By the way, because your `.bazelci/presubmit.yml` is versioned with your repository, you can easily test config changes by sending a PR. This will trigger a CI run, which will then already use the config. Once it's working as intended, just merge. :)

**Comment by philwo** [comment] 2019-10-09 12:12
Closing this, because I think everything has been done - please let me know if there's something missing :)

**Closed by philwo** 2019-10-09 12:12 UTC
Labels: new-project
