### ISSUE TITLE
Request to add new project rules_qt

### ISSUE THREAD

**Issue by limdor** [bazelbuild/continuous-integration#1078] opened 2021-01-02 12:28 UTC
- I want to test the following project on Bazel CI: https://github.com/limdor/bazel_rules_qt
- I confirm that the project has a `.bazelci/presubmit.yml` file.

**Comment by fweikert** [comment] 2021-01-18 15:33
Are there any plans to merge your changes into the upstream project https://github.com/justbuchanan/bazel_rules_qt?

I'm just wondering which project should be tested here.

**Comment by fweikert** [comment] 2021-01-18 15:45
I created https://buildkite.com/bazel/rules-qt since we can change the repo later, if needed. 

If you send me an email to fwe@$searchcompany.com I can add you as a pipeline admin, which allows you to set up GitHub integration for presubmit.

**Comment by limdor** [comment] 2021-01-18 19:57
Hi @fweikert thanks for taking it. About your question, I still did not talk with @justbuchanan about how to do it. My plan is to contribute the upstream, indeed I already created a PR for it and I'm planning to create more https://github.com/justbuchanan/bazel_rules_qt/pull/9.
I would like to request at some point to be inside bazelbuild organization, but for that it needs to go to the bazelci and this is why I created this PR. About which of the repo we take as a base, I'm sure we will find some agreement.

Regarding the presubmit setup using buildkite I see some possible issues on making it work because currently the rules for Qt rely on Qt being preinstalled in the build machine and I am not sure if it is possible. I wanted to create this ticket to start trying it out and trigger the discussion. Can I add some section where some package is installed before the execution gets installed? Is there any example for it around that you are aware?

**Comment by fweikert** [comment] 2021-01-19 16:16
There are basically two approaches:

1. Fetch dependencies during each build (e.g. https://github.com/plaidml/plaidml/blob/master/.bazelci/presubmit.yml)
2. Add dependencies to our docker images at https://github.com/bazelbuild/continuous-integration/tree/master/buildkite/docker

In the end it's a trade-off between presubmit performance vs docker image size. Approach 1 makes it easier to iterate, too, since for 2 we'd need to redeploy Docker images whenever something changes.

**Comment by limdor** [comment] 2021-01-23 11:45
Thanks @fweikert I will try to go first for option 1.
Is there an option to install stuff as root? The easiest way would have been to install qt from apt-get doing:
`sudo apt-get install qt5-default`
but I saw that sudo does not work.
If not I will try to install it using the offline installers and see if I can do it without root.
I still should be able

**Comment by fweikert** [comment] 2021-03-30 13:42
Does this issue require any actions from our side?

**Comment by limdor** [comment] 2021-03-30 16:07
I had the issue that git commit status was automatically deactivated because of 404 spamm. I tried to follow the instructions but I did not manage. I send you an email but maybe it got lost.
In the meantime I ported all changes to the original fork of rules_qt, @justbuchanan is the original maintainer, maybe we could just change it to point directly to https://github.com/justbuchanan/bazel_rules_qt, it also has a bazel ci file.
Not sure if it is worth to fight with the commit status if in the end we would like to make it point to the original repo. @justbuchanan what do you think?

**Comment by justbuchanan** [comment] 2021-03-30 16:33
If it's not too much trouble to set this up for https://github.com/justbuchanan/bazel_rules_qt, that would be great! Let me know if I can help.

**Comment by fweikert** [comment] 2021-04-01 11:15
I changed the existing pipeline to use the upstream repo: https://buildkite.com/bazel/rules-qt/builds/70

**Comment by justbuchanan** [comment] 2021-04-04 18:21
Thanks for setting this up, @fweikert. Is there a way to get bazel ci to show status checks for PRs against the main repo? I opened https://github.com/justbuchanan/bazel_rules_qt/pull/22 for example and I don't see status checks or any new builds on https://buildkite.com/bazel/rules-qt.

**Comment by fweikert** [comment] 2021-04-07 19:08
Yes, I just activated that setting.

**Comment by fweikert** [comment] 2021-04-07 19:23
@limdor / @justbuchanan  : Have you connected your GitHub account to Buildkite via the Buildkite GitHub Application ( https://buildkite.com/organizations/bazel/repository-providers)?

I'm trying to figure out why I don't see any commit status updates on GitHub. Usually Buildkite complains about 404s, but that's not the case here.

If you haven't done so, you can also invite @bazel-io as collaboratorm which should work (I'm currently testing this approach).

**Comment by justbuchanan** [comment] 2021-04-08 02:10
I tried to connect my account, but when I follow that buildkite link, I get an error message: "You're not allowed to change this organization", which makes sense since it's the "bazel" org.

I added @bazel-io as a collaborator - will that run some automation to configure PR status checks, etc?

**Comment by fweikert** [comment] 2021-04-08 16:30
It works: https://github.com/justbuchanan/bazel_rules_qt/pull/22

**Comment by limdor** [comment] 2021-04-08 17:35
Nice, now we just need to make the build green ;-)

**Comment by fweikert** [comment] 2021-04-08 18:14
Sounds like a plan :) I'll close this issue since we finished onboarding. Please let me know if further assistance is needed.

**Comment by justbuchanan** [comment] 2021-04-22 00:18
Hi Florian, sorry for the slow followup. It looks like commit statuses are correctly being updated for PRs when a buildkite build happens (so far only via manual trigger), but pushing new commits / creating a PR still isn't triggering builds. I think we're missing some configuration on the buildkite pipeline side, but I'm not able to edit settings on there - would you mind adding me as an editor on the pipeline? Thanks!

**Comment by fweikert** [comment] 2021-04-27 16:17
IIRC the webhooks were only set up for the temporary repository.

I added you to the rules_qt team. Can you access and please execute the [instructions](https://buildkite.com/bazel/rules-qt/settings/setup/github) ?

**Comment by justbuchanan** [comment] 2021-04-27 17:11
Thanks! I got the buildkite invite in my email, but when I go to https://buildkite.com/bazel/rules-qt, I don't see the button for "Pipeline Settings": ![bk](https://user-images.githubusercontent.com/115131/116283359-a9982c80-a740-11eb-9658-12008f2f5a09.png)

Following the [webhook instructions link](https://buildkite.com/bazel/rules-qt/settings/setup/github) shows me: 
![bk2](https://user-images.githubusercontent.com/115131/116283559-dd735200-a740-11eb-8785-b8e40f0cd4b0.png)

**Comment by fweikert** [comment] 2021-04-27 17:23
I updated the permissions - can you please try again?

**Comment by justbuchanan** [comment] 2021-04-27 17:36
I was able to setup the webhooks and confirmed that my latest push to justbuchanan/bazel_rules_qt#22 automatically triggered a build. Looks like this is all working now, thanks!

**Comment by fweikert** [comment] 2021-04-28 13:57
Great!

**Closed by fweikert** 2021-04-28 13:57 UTC
Labels: new-project

**Comment by philwo** [comment] 2021-06-30 10:02
Hi @justbuchanan,

the rules_qt pipeline has been red on Bazel CI for a while. We can't get a test signal for Bazel from this project if the pipeline is red, unfortunately, so we can't test that changes we make don't accidentally break your rules. What's the status on this?

Cheers,
Philipp

**Comment by limdor** [comment] 2021-06-30 18:21
Sorry I was pushing for this to be in the CI but unfortunately I did not have time to continue on the whole toolchain for Qt.
The point is that the Bazel CI does not have a normal Qt installation, it needs to be installed in a special way that then is not in the path. This is a fair use case but requires that rules_qt supports this case. The alternative was to request Qt to be installed in the docker but this was considered a bit overhead for the rest of the jobs using the same docker.
If the additional resources is not a big issue, and the main issue is the permanent failing (that I perfectly understand) I would propose for the moment to not build any target: https://github.com/justbuchanan/bazel_rules_qt/pull/33
This has the advantage that @justbuchanan, me or whoever wants to contribute can try to fix it and test against the Bazel CI. However from my side I cannot commit on a specific date, I am doing it only on my free time. The other option would be to remove it from the Bazel CI completely and request to put it back once it is fix.
@justbuchanan what do you think?

**Comment by justbuchanan** [comment] 2021-12-18 20:57
Apologies for ignoring this for so long. I finally got around to it this morning and was able to fix the build by installing dependencies with `apt`. See https://github.com/justbuchanan/bazel_rules_qt/commit/1414d50dcdc15128f0ccd4d317b8aa48b89573ed.
