### ISSUE TITLE
rules_foreign_cc (examples) failing on macOS in downstream pipeline

### ISSUE THREAD

**Issue by Wyverald** [bazelbuild/continuous-integration#1428] opened 2022-09-08 17:48 UTC
Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2615#01831adf-c5cd-4ec5-9802-aaa52dc2a45d

Culprit finder ([run link](https://buildkite.com/bazel/culprit-finder/builds/3520#01831cf6-6e27-45dd-b936-7db357443728)) points to this commit: https://github.com/bazelbuild/bazel/commit/cbb24d5ad6ef154e4c8118cdcba68cbb042463ed which doesn't really make sense. Might be a flake; I'll do another culprit finder run.

**Comment by Wyverald** [comment] 2022-09-09 12:36
Another culprit finder run, same result: https://buildkite.com/bazel/culprit-finder/builds/3521#01831e3d-a49c-4dc2-bba2-3ba608637a34 :/

**Comment by meteorcloudy** [comment] 2022-09-12 15:58
The actual error never shows up in the log "FATAL: bazel crashed due to an internal error."

It returns `cbb24d5ad6ef154e4c8118cdcba68cbb042463ed` because the binary is missing at this commit
```
gsutil cp gs://bazel-builds/artifacts/macos/cbb24d5ad6ef154e4c8118cdcba68cbb042463ed/bazel /tmp/tmpycpli313/bazel

CommandException: No URLs matched: gs://bazel-builds/artifacts/macos/cbb24d5ad6ef154e4c8118cdcba68cbb042463ed/bazel

Failed to download Bazel binary at cbb24d5ad6ef154e4c8118cdcba68cbb042463ed, error message:

Command '['gsutil', 'cp', 'gs://bazel-builds/artifacts/macos/cbb24d5ad6ef154e4c8118cdcba68cbb042463ed/bazel', '/tmp/tmpycpli313/bazel']' returned non-zero exit status 1.

```

**Comment by meteorcloudy** [comment] 2022-09-12 16:03
And cbb24d5ad6ef154e4c8118cdcba68cbb042463ed wasn't built because tony merged three commits together...

**Comment by meteorcloudy** [comment] 2022-09-12 16:11
And of course the first two commits are not even buildable..

**Comment by meteorcloudy** [comment] 2022-09-12 16:11
Anyway, the culprit finder doesn't seem to work, we'll have to reproduce manually

**Comment by meteorcloudy** [comment] 2022-09-13 13:57
This is a legit Bazel issue, as the bisect range shifted, the culprit finder has identified the correct culprit (hopefully):
https://buildkite.com/bazel/culprit-finder/builds/3570#01833508-0419-4ca3-a6c1-19f5b143383a
```
commit 8e674324d18b715fd09c7fcfedd97be28caa525c
Author: Googler <wilwell@google.com>
Date:   Wed Aug 24 04:46:58 2022 -0700
 
    Control worker lifecycle via `WorkerLifecycleManager`.
 
    We want to control the abusing of resources (e.g. memory) by workers, so we decided to start with total memory limit for all workers. To control this use the option `experimental_total_worker_memoty_limit_mb`.
 
    To do it we use standard `evict()` function of `GenericKeyedObjectPool`. Indeed we use this call twice: first to collect the idle workers, and for the second time to evict the largest idle workers.
 
    PiperOrigin-RevId: 469693732
    Change-Id: Ib0e51587f6b1744b128678f6e341964820bb1aec
```

**Comment by meteorcloudy** [comment] 2022-09-13 14:01
Closing in favor of https://github.com/bazelbuild/bazel/issues/16267

**Closed by meteorcloudy** 2022-09-13 14:01 UTC
