### ISSUE TITLE
No space left on device when compiling LLVM

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/continuous-integration#1379] opened 2022-06-17 12:24 UTC
We are consistently seeing `No space left on device` (which file exactly hits the error varies between builds, which is expected) in our Ubuntu 20.04 builds of LLVM. We know LLVM is a large codebase. For example my `bazel-out` is currently 3GB. It should be still far below the disk size in Ubuntu workers, which I'm told have 500GB disks. Any help here would be greatly appreciated :)

Project: http://github.com/google/crubit
Example CI run: https://buildkite.com/bazel/crubit/builds/40#0181669a-f666-4d2f-b5a7-15649d6a419a

**Comment by fweikert** [comment] 2022-08-17 12:40
Has this error happened again? For the most recent runs I see "The current `lockfile` is out of date for 'crate_index'."

**Comment by hlopko** [comment] 2022-08-22 07:36
I believe it is still happening, but now we have accumulated breakages that I need to fix first. I'll ping this issue once that's done.

**Comment by meteorcloudy** [comment] 2022-08-26 11:42
Is it possible to reproduce this with the `gcr.io/bazel-public/ubuntu2004-java11` docker container locally on your machine?

**Comment by meisterT** [comment] 2022-08-26 12:40
I was able to repro locally and dig into the error. It took me a while to figure this out and was first guessing that this would be inode related.

The actual cause of it is this line of your bazelrc: https://github.com/google/crubit/blob/main/.bazelrc#L12

Your setting the sandbox base to `/dev/shm` which at least in my docker container is `64M`, so easy to fill up :-)

@meteorcloudy 
See https://www.deepanseeralan.com/tech/changing-shmem-size-of-docker-container/ for a way to increase this on CI

@hlopko 
While Yun is figuring out whether this is a viable solution, you can just uncomment that line?

Alos the build still fails, but this looks like a legitimate issue to me, see https://gist.github.com/meisterT/a8e6fb38d00d3b2f0f804920156252ba

**Comment by meteorcloudy** [comment] 2022-08-26 12:43
Nice catch! Thanks, @meisterT !

> While Yun is figuring out whether this is a viable solution, you can just uncomment that line?

I wonder whether we should do that. @hlopko Do you know why `--sandbox_base=/dev/shm` was set? Does it make sense on CI?

**Comment by hlopko** [comment] 2022-08-26 13:35
Wow many thanks to all of you (and also one big facepalm for me, I could have thought about that)!

I believe this was there as a local build performance optimization, I see instances of this flag around, for example in the LLVM repo (https://github.com/llvm/llvm-project/blob/main/utils/bazel/.bazelrc#L159), where it is specifically on the `ci` config. I dont' have the data on how much it speeds up the build right now. In some bespoke docs I see that for LLVM it is recommended to have at least 1 GB of ramdisk. It probably depends on how many actions are running in parallel on the worker.

**Comment by meteorcloudy** [comment] 2022-08-26 14:39
IIRC, TensorFlow also depends on LLVM, but we don't have the optimization enabled for it. Maybe it's also no necessary for Crubit?

**Comment by hlopko** [comment] 2022-08-26 14:43
It's definitely not necessary, it's just an optimization. In fact I already have a change in flight to disable it for Crubit. I assumed I was only doing it to unblock our CI runs, but if that's your recommendation I'm happy to keep it disabled. I may come back with build time data with and without the flag once we have a green build. At the end we still like fast builds and fewer wasted resources :)

**Comment by hlopko** [comment] 2022-08-26 14:46
(I'm happy to reopen the issue if you want to close it for now, up to you)

**Comment by meteorcloudy** [comment] 2022-08-26 14:56
OK, since there is no action needed from us for now, we can close it, feel free to reopen.

**Closed by meteorcloudy** 2022-08-26 14:56 UTC
