### ISSUE TITLE
rules_haskell broken Bazel@HEAD

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/continuous-integration#1090] opened 2021-02-08 21:33 UTC
rules_haskell is broken on Bazel@HEAD and it looks like infra issues:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1903#81e5c204-6ddf-4452-85a5-65b950176c5a

```
ghc-check: user error (GHC installation not found in libdir: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d75b0331de3f05f7e216b484840495e7/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib)
```

Not sure how to go about diagnosing / debugging this...

**Comment by meteorcloudy** [comment] 2021-02-09 10:50
I tried to reproduce in a docker container on one of the VM on Bazel CI. 
It can only be reproduced with remote cache enabled, so it looks like a cache posion.
Maybe it's time to update https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/bazelci.py#L1487 again?

**Comment by comius** [comment] 2021-02-15 11:18
On Friday & Saturday 2020-02-13 rules_haskell build failed with:
```
(04:07:33) ERROR: /var/lib/buildkite-agent/builds/bk-docker-bwlz/bazel-downstream-projects/rules_haskell/tests/haddock/BUILD.bazel:53:12: Action tests/haddock/haddock/integer-gmp-1.0.2.0 failed: Exec failed due to IOException: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/6ecbf9465bc2a3248fe1ad6ad26577cc/execroot/rules_haskell/rules_haskell/external/rules_haskell_ghc_linux_amd64/doc/html/libraries/integer-gmp-1.0.2.0 (No such file or directory)
```

**libraries/base-4.13.0.0**

On Sunday & Monday 2020-02-15, rules_haskel build fails with:
```
/var/lib/buildkite-agent/builds/bk-docker-9xbs/bazel-downstream-projects/rules_haskell/tests/haddock_protobuf/BUILD.bazel:43:12: Action tests/haddock_protobuf/haddocks_b/base-4.13.0.0 failed: Exec failed due to IOException: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/d39aff51c903444f5ecd05df031547dd/execroot/rules_haskell/rules_haskell/external/rules_haskell_ghc_linux_amd64/doc/html/libraries/base-4.13.0.0 (No such file or directory)
```

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1914#b45cae9a-86a7-4b0e-8d2b-fcdd812eed09

**Comment by philwo** [comment] 2021-02-16 10:46
[Auto-Sheriff](https://buildkite.com/bazel/bazel-auto-sheriff-face-with-cowboy-hat/builds/431) identified this commit as the culprit: https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe

**Comment by comius** [comment] 2021-02-18 14:30
The error changed today from missing **libraries/base-4.13.0.0** to missing **libraries/array-0.5.4.0**. Where there some changes on the infrastructure? Or is this result of some flakiness?

**Comment by meteorcloudy** [comment] 2021-02-18 16:09
rules_haskell did go back to green for a short time after I updated the cache poisoning key:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1903#d2127bfa-a988-4084-9fb9-61459d522331

I don't know what poisoned it again..

**Comment by meteorcloudy** [comment] 2021-02-19 12:28
This is now fixed.
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1924

**Comment by comius** [comment] 2021-02-19 12:30
Wait, it's not fixed.

**Comment by meteorcloudy** [comment] 2021-02-19 12:38
Ah, the error caused by bazelbuild/bazel@7149f57 is fixed. The current error seems to be a cache poisoning.

**Closed** 2021-02-19 13:18 UTC
